[build]
    functions = "functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/app/api/v1/:splat"
  status = 200
